theme: jekyll-theme-minimal
title: tiffany's git-pages
description: proffessionally an idiot
remote_theme: ImgTypeTiff/jekyll-tiff-simple-dark
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
