theme: jekyll-theme-minimal
title: tiffany's git-pages
description: proffessionally an idiot
remote_theme: son-link/jekyll-simple-dark
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
paginate: 5
