theme: jekyll-theme-minimal
title: tiffany's git-pages
description: proffessionally an idiot
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
remote_theme: ImgTypeTiff/jekyll-tiff-simple-dark
paginate: 5
